modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="hordes"
version="1.1.4a"
displayName="The Hordes"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-hordes"
updateJSONURL="https://raw.githubusercontent.com/SmileycorpMC/The-Hordes/1.16/update.json"
credits="bstylia14, Ski_Z"
authors="Smileycorp"
description="Adds mob horde invasions and zombie infections to the game."

[[dependencies.hordes]]
    modId="atlaslib"
    mandatory=true
    versionRange="[1.1.3b,)"
    ordering="NONE"
    side="BOTH"
